spring:
  security:
    secret: ${SECURITY_SECRET_KEY}
    expiration: 8640000
  datasource:
    url: jdbc:mysql://localhost:3306/memo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      connection.provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
      hibernate:
        format_sql: true
